//
//  DataModel.swift
//  DeepDive
//
//  Created by Mateusz Rybczyński on 23/12/2024.
//

import Foundation
import SwiftUI

struct Question: Identifiable {
    let id = UUID()
    let text: LocalizedStringKey
    let subtitle: LocalizedStringKey?
    let themeColor: String
    let category: String
    let image: String
    let backgroundColor: String
}


class QuestionStore: ObservableObject {
    @Published var questions: [Question] = [
        //Dla par
        Question(text: "DlaPar1", subtitle: "DlaParSub1", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar2", subtitle: "DlaParSub2", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar3", subtitle: "DlaParSub3", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar4", subtitle: "DlaParSub4", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar5", subtitle: "DlaParSub5", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar6", subtitle: "DlaParSub6", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar7", subtitle: "DlaParSub7", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar8", subtitle: "DlaParSub8", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar9", subtitle: "DlaParSub9", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar10", subtitle: "DlaParSub10", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar11", subtitle: "DlaParSub11", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar12", subtitle: "DlaParSub12", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar13", subtitle: "DlaParSub13", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar14", subtitle: "DlaParSub14", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar15", subtitle: "DlaParSub15", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar16", subtitle: "DlaParSub16", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar17", subtitle: "DlaParSub17", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar18", subtitle: "DlaParSub18", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar19", subtitle: "DlaParSub19", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar20", subtitle: "DlaParSub20", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar21", subtitle: "DlaParSub21", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar22", subtitle: "DlaParSub22", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar23", subtitle: "DlaParSub23", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar24", subtitle: "DlaParSub24", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar25", subtitle: "DlaParSub25", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar26", subtitle: "DlaParSub26", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar27", subtitle: "DlaParSub27", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar28", subtitle: "DlaParSub28", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar29", subtitle: "DlaParSub29", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar30", subtitle: "DlaParSub30", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar31", subtitle: "DlaParSub31", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar32", subtitle: "DlaParSub32", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar33", subtitle: "DlaParSub33", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar34", subtitle: "DlaParSub34", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar35", subtitle: "DlaParSub35", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar36", subtitle: "DlaParSub36", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar37", subtitle: "DlaParSub37", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar38", subtitle: "DlaParSub38", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar39", subtitle: "DlaParSub39", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        Question(text: "DlaPar40", subtitle: "DlaParSub40", themeColor: "BlackColor", category: "dlapar", image: "loveheart", backgroundColor: "dlapar"),
        // Cienie
        Question(text: "Cienie1", subtitle: "CienieSub1", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie2", subtitle: "CienieSub2", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie3", subtitle: "CienieSub3", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie4", subtitle: "CienieSub4", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie5", subtitle: "CienieSub5", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie6", subtitle: "CienieSub6", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie7", subtitle: "CienieSub7", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie8", subtitle: "CienieSub8", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie9", subtitle: "CienieSub9", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie10", subtitle: "CienieSub10", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie11", subtitle: "CienieSub11", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie12", subtitle: "CienieSub12", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie13", subtitle: "CienieSub13", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie14", subtitle: "CienieSub14", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie15", subtitle: "CienieSub15", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie16", subtitle: "CienieSub16", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie17", subtitle: "CienieSub17", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie18", subtitle: "CienieSub18", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie19", subtitle: "CienieSub19", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie20", subtitle: "CienieSub20", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie21", subtitle: "CienieSub21", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie22", subtitle: "CienieSub22", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie23", subtitle: "CienieSub23", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie24", subtitle: "CienieSub24", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie25", subtitle: "CienieSub25", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie26", subtitle: "CienieSub26", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie27", subtitle: "CienieSub27", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie28", subtitle: "CienieSub28", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie29", subtitle: "CienieSub29", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie30", subtitle: "CienieSub30", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie31", subtitle: "CienieSub31", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie32", subtitle: "CienieSub32", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie33", subtitle: "CienieSub33", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie34", subtitle: "CienieSub34", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie35", subtitle: "CienieSub35", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie36", subtitle: "CienieSub36", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie37", subtitle: "CienieSub37", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie38", subtitle: "CienieSub38", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie39", subtitle: "CienieSub39", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        Question(text: "Cienie40", subtitle: "CienieSub40", themeColor: "BlackColor", category: "cienie", image: "ghost", backgroundColor: "cienie"),
        // Wyznania
        Question(text: "Wyznania1", subtitle: "WyznaniaSub1", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania2", subtitle: "WyznaniaSub2", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania3", subtitle: "WyznaniaSub3", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania4", subtitle: "WyznaniaSub4", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania5", subtitle: "WyznaniaSub5", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania6", subtitle: "WyznaniaSub6", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania7", subtitle: "WyznaniaSub7", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania8", subtitle: "WyznaniaSub8", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania9", subtitle: "WyznaniaSub9", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania10", subtitle: "WyznaniaSub10", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania11", subtitle: "WyznaniaSub11", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania12", subtitle: "WyznaniaSub12", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania13", subtitle: "WyznaniaSub13", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania14", subtitle: "WyznaniaSub14", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania15", subtitle: "WyznaniaSub15", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania16", subtitle: "WyznaniaSub16", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania17", subtitle: "WyznaniaSub17", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania18", subtitle: "WyznaniaSub18", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania19", subtitle: "WyznaniaSub19", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania20", subtitle: "WyznaniaSub20", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania21", subtitle: "WyznaniaSub21", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania22", subtitle: "WyznaniaSub22", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania23", subtitle: "WyznaniaSub23", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania24", subtitle: "WyznaniaSub24", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania25", subtitle: "WyznaniaSub25", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania26", subtitle: "WyznaniaSub26", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania27", subtitle: "WyznaniaSub27", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania28", subtitle: "WyznaniaSub28", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania29", subtitle: "WyznaniaSub29", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania30", subtitle: "WyznaniaSub30", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania31", subtitle: "WyznaniaSub31", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania32", subtitle: "WyznaniaSub32", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania33", subtitle: "WyznaniaSub33", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania34", subtitle: "WyznaniaSub34", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania35", subtitle: "WyznaniaSub35", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania36", subtitle: "WyznaniaSub36", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania37", subtitle: "WyznaniaSub37", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania38", subtitle: "WyznaniaSub38", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania39", subtitle: "WyznaniaSub39", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        Question(text: "Wyznania40", subtitle: "WyznaniaSub40", themeColor: "BlackColor", category: "wyznania", image: "door", backgroundColor: "wyznania"),
        // Party
        Question(text: "Party1", subtitle: "PartySub1", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party2", subtitle: "PartySub2", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party3", subtitle: "PartySub3", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party4", subtitle: "PartySub4", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party5", subtitle: "PartySub5", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party6", subtitle: "PartySub6", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party7", subtitle: "PartySub7", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party8", subtitle: "PartySub8", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party9", subtitle: "PartySub9", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party10", subtitle: "PartySub10", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party11", subtitle: "PartySub11", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party12", subtitle: "PartySub12", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party13", subtitle: "PartySub13", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party14", subtitle: "PartySub14", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party15", subtitle: "PartySub15", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party16", subtitle: "PartySub16", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party17", subtitle: "PartySub17", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party18", subtitle: "PartySub18", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party19", subtitle: "PartySub19", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party20", subtitle: "PartySub20", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party21", subtitle: "PartySub21", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party22", subtitle: "PartySub22", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party23", subtitle: "PartySub23", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party24", subtitle: "PartySub24", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party25", subtitle: "PartySub25", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party26", subtitle: "PartySub26", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party27", subtitle: "PartySub27", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party28", subtitle: "PartySub28", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party29", subtitle: "PartySub29", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        Question(text: "Party30", subtitle: "PartySub30", themeColor: "BlackColor", category: "party", image: "party", backgroundColor: "party"),
        // Simple
        Question(text: "Simple1", subtitle: "SimpleSub1", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple2", subtitle: "SimpleSub2", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple3", subtitle: "SimpleSub3", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple4", subtitle: "SimpleSub4", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple5", subtitle: "SimpleSub5", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple6", subtitle: "SimpleSub6", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple7", subtitle: "SimpleSub7", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple8", subtitle: "SimpleSub8", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple9", subtitle: "SimpleSub9", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple10", subtitle: "SimpleSub10", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple11", subtitle: "SimpleSub11", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple12", subtitle: "SimpleSub12", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple13", subtitle: "SimpleSub13", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple14", subtitle: "SimpleSub14", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple15", subtitle: "SimpleSub15", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple16", subtitle: "SimpleSub16", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple17", subtitle: "SimpleSub17", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple18", subtitle: "SimpleSub18", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple19", subtitle: "SimpleSub19", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple20", subtitle: "SimpleSub20", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple21", subtitle: "SimpleSub21", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple22", subtitle: "SimpleSub22", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple23", subtitle: "SimpleSub23", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple24", subtitle: "SimpleSub24", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple25", subtitle: "SimpleSub25", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple26", subtitle: "SimpleSub26", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple27", subtitle: "SimpleSub27", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple28", subtitle: "SimpleSub28", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple29", subtitle: "SimpleSub29", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple"),
        Question(text: "Simple30", subtitle: "SimpleSub30", themeColor: "BlackColor", category: "simple", image: "simple", backgroundColor: "simple")
    ]
}
